services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    container_name: antizapret-vpn
    hostname: antizapret
    restart: unless-stopped
    privileged: true
    stop_signal: SIGRTMIN+4
    build: .
    environment:
      - DNS
      - DNS_RU
      - ADGUARD
      - LOG_DNS
      - SKIP_UPDATE_FROM_ZAPRET
      - UPDATE_TIMER
#    dns:
#      - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./antizapret_config:/root/antizapret/config/custom
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2