services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    container_name: antizapret-vpn
    hostname: antizapret
    restart: unless-stopped
    privileged: true
    stop_signal: SIGRTMIN+4
    build: .
    environment:
      - DNS
      - DNS_RU
      - ADGUARD
      - LOG_DNS
      - SKIP_UPDATE_FROM_ZAPRET
      - UPDATE_TIMER
#    dns:
#      - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./antizapret_config:/root/antizapret/config/custom
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
  
  openvpn:
    image: xtrime/openvpn
    build:
      context: .
      dockerfile: Dockerfile.openvpn
      args:
        TARGETOS: linux
        TARGETARCH: amd64
    container_name: openvpn
    environment:
      - OPENVPN_ADMIN_USERNAME=admin # Default username web ui
      - SITE_NAME=Admin # Title web ui
      - AUTO_INITIAL=1 # Auto initial (clean to install via wizard)
      - OPENVPN_PORT # Port openvpn server, default 1194
      - URL_PREFIX # URL prefix to admin ui, example: /admin-openvpn
      - APP_PORT # Set web ui port
      - CK_ENABLE=1 # =1 if enable Cloak
      - CK_UID # Set client UID or generate
      - CK_ADMIN_UID # Set ADMIN UID or generate
      - CK_PRIVATE_KEY # Set PK or generate
      - CK_REDIR_ADDR # Set redirect addr or cloudflare.com
    env_file:
      - ./openvpn/.env
    ports:
      - "8080:8080/tcp" # For web ui
      - "443:443/tcp" # For Cloak
      - "80:80/tcp" # For Cloak
      - "1194:1194/udp" # For OpenVPN
    restart: unless-stopped
    privileged: true
    stop_signal: SIGRTMIN+4
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn/scripts:/opt/scripts
      - ./openvpn_config/conf:/etc/openvpn
      - ./openvpn_config/db:/opt/openvpn-gui/db
      - ./openvpn_config/cloak:/opt/cloak/conf
    depends_on:
      - antizapret-vpn
